@startuml

entity User {
  * id: int: <<PK>>
  --
  * phone: str
  * password_hash: str

  * name: str
  * rating: double
  * favorite_genres: list[str]

  talkativeness: int 0-10
  attitude towards smoking: int 0-10
  attitude towards animals during the trip: int 0-10

  avatar: path to file
  __

}

entity Trip {
  * id: int <<PK>>
  --
  * departure_place: geo
  * departure_datetime: datetime
  * arrival_place: geo
  * arrival_datetime: datetime
  * max_passengers

  * cost: int
  * stops: list[?]

  max two passengers in the back seat: bool
  smoking_allowed: bool
  e-cigarettes_allowed: bool
  pets_allowed: bool
  free_trunk: bool
  __
  * car_id <<FK>>
  * driver_id <<FK>>
}

entity Car {
  * id: int <<PK>>
  --
  * brand: str
  * model: str
  * color: rgb
  * year_of_manufacture: int
  * photo: list[path]

  __
  * user_id: int <<FK>>
}

entity Request {
  * id: int <<PK>>
  --
  * request_datetime: datetime
  * status: enum(Created, Accepted, Declined, Finished)
  * status_change_datetime: datetime
  * cost: int
  * number_of_seats: int

  * departure: geo
  * arrival: geo
  __
  * trip_id: int <<FK>>
  * user_id: int <<FK>>
}

User ||..o{ Car
Trip ||..|| Car
Trip ||..|| User
Trip ||..o{ Request
User ||..o{ Request


entity Chat {
  * id <<PK>>
  --
  __
 * user_id_1 <<FK>>
 * user_id_2 <<FK>>
}

entity ChatMessage {
  * id
  --
  text: str
  img: path
  __
  * sender_id <<FK>>
  * chat_id <<FK>>
}

User ||..o{ Chat
ChatMessage ||..|| User
ChatMessage ||..|| User

entity Review {
 * id <<PK>>
 --
 text: str
 rating: int
 __
 * writer_id: int <<FK>>
 * user_id: int <<FK>>
}

Review ||..|| User
Review ||..|| User

entity Payment {
  * id: int
  * amount: int
  --
  * amount: int
  * status: enum [CREATED, OK, RETURNED]
  __
  * payment_id: int <<FK>>
  * request_id: int <<FK>>
  * user_id: int <<FK>>
}

Payment ||..|| User
Payment ||..|| Request


entity PaymentMethod {
  * id: int <<PK>>
  --
  * data_json: str[json]
  __
  * user_id <<FK>>
}

User ||..o{ PaymentMethod

@enduml
